CREATE TABLE  WS_DESTINO(
	ID NUMBER CONSTRAINT DESTINO_PK PRIMARY KEY,
	PAIS VARCHAR2(50) NOT NULL,
	CIUDAD VARCHAR2(50) NOT NULL,
	CLIMA VARCHAR2(50) NOT NULL
);

CREATE TABLE  USUARIO(
	ID NUMBER CONSTRAINT USUARIO_PK PRIMARY KEY,
	NOMBRE VARCHAR2(50) NOT NULL,
	DIRECCION VARCHAR2(50) NOT NULL,
	CIUDAD VARCHAR2(50) NOT NULL,
	PAIS VARCHAR2(50) NOT NULL,
	EDAD NUMBER(8) NOT NULL,
	TELEFONO NUMBER(8) NOT NULL,
	EMAIL VARCHAR2(50) NOT NULL,
	USUARIO VARCHAR2(50) NOT NULL,
	ROL NUMBER(8) NOT NULL,
	PASSWORD VARCHAR2(50) NOT NULL
);

CREATE TABLE  VIAJE(
	ID NUMBER CONSTRAINT VIAJE_PK PRIMARY KEY,
	NOMBRE VARCHAR2(50) NOT NULL,
	FOTO BLOB,
	DESCRIPCION VARCHAR2(50) NOT NULL,
	CUPO_MAXIMO NUMBER(8) NOT NULL,
	DISPONIBILIDAD NUMBER(8) NOT NULL,
	FECHA_INCIO DATE NOT NULL,
	FECHA_FIN DATE NOT NULL,
	PRECIO NUMBER(8) NOT NULL,
	ORIGEN VARCHAR2(50) NOT NULL,
	ID_WS_DESTINO NUMBER CONSTRAINT VIAJE_WS_DESTINO_FK REFERENCES WS_DESTINO(ID)
);

CREATE TABLE  COMPRA(
	ID NUMBER CONSTRAINT COMPRA_PK PRIMARY KEY ,
	ID_VIAJE NUMBER CONSTRAINT COMPRA_VIAJE_FK REFERENCES VIAJE(ID) ON DELETE SET NULL,
	ID_USUARIO NUMBER CONSTRAINT COMPRA_USUARIO_FK REFERENCES USUARIO(ID) ON DELETE SET NULL
);

CREATE SEQUENCE HIBERNATE_SEQUENCE
START WITH 1  INCREMENT BY 1;